### ISSUE TITLE
How do you invert the colors and how do you name the bluetooth profiles?

### ISSUE THREAD

**Issue by dani4ko03** [infely/nice-view-battery#1]
I was looking though your code and through both the zmk docs and your docs and was unable to find how to change either of these things. I saw that in one of the images you had a name in the bar above that said GAME and I am assuming that is the Bluetooth profile name. Please help me with changing these two things.

**Comment by infely** [comment]
I've added a description of how to invert colors to the README.

Not exactly. The screenshot demonstrates the layer name, not the Bluetooth profile. This can be useful if you use sticky layers.

**Comment by dani4ko03** [comment]
how do you change the layer name or remove the area for it because at the moment its just a blank grey line. Also where do you add that variable to, which config file?

**Comment by infely** [comment]
You can comment out or set the `display-name` in your keymap file.

Example:

```
game_layer {
  display-name = "Game";
  bindings = <
    // ...
  >;
};
```

**Comment by dani4ko03** [comment]
inverting the colors does not invert the whole screen and an a blank layer name does not get rid of the field name but rather just remains as an empty square.
![20241027_160717](https://github.com/user-attachments/assets/8689ab87-1c81-4fa0-95b6-05bdc0e95526)

**Comment by infely** [comment]
Update your fork or use this repository. You can set variables in your config file.

To hide a layer, the display name should be removed, not set to an empty string (hiding only works for the first layer)

**Comment by dani4ko03** [comment]
even thought the display name line is removed from the keymap the empty bar is still display on screen.
This is layer 1:
![20241027_164527](https://github.com/user-attachments/assets/67645fd4-393f-4cd9-8647-a193d8517c14)
This is layer 0: 
![20241027_164522](https://github.com/user-attachments/assets/565a486e-483b-4d8d-b219-7bca41e950f1)
 and this is the code with the commented-out display name variable:

#include <behaviors.dtsi>
#include <dt-bindings/zmk/keys.h>
#include <dt-bindings/zmk/bt.h>

/ {
        keymap {
                compatible = "zmk,keymap";

                default_layer {
                        //display-name = "Letters";
                        bindings = <
   &kp TAB   &kp Q &kp W &kp E &kp R &kp T   &kp Y &kp U  &kp I     &kp O   &kp P    &kp BSPC
   &kp LCTRL &kp A &kp S &kp D &kp F &kp G   &kp H &kp J  &kp K     &kp L   &kp SEMI &kp SQT
   &kp LSHFT &kp Z &kp X &kp C &kp V &kp B   &kp N &kp M  &kp COMMA &kp DOT &kp FSLH &kp ESC
                  &kp LGUI &mo 1 &kp SPACE   &kp RET &mo 2 &kp RALT
                        >;
                };
                lower_layer {
                        display-name = "Number";
......

**Comment by infely** [comment]
I updated the check for the empty layer, try again.

**Comment by dani4ko03** [comment]
The empty layer works now. 

The inverted color layer is missing a padding and the icons are pressed against the outside boarder of the display. I am interested in using the inverted white colors in order to save on battery life. I will try and add padding to it eventually, after I figure out all the code a little more, so it looks a little more appealing, but for now, I just thought I would let you know.
